template: true   # required for local templates
valuesFilePath: ./values.yml

pipelines:
  - name: gradle_pipelines_test
    configuration:
      runtime:
        type: image
        image:
          custom:
            name: docker.jfrog.io/jfrog/pipelines-u20java
            tag: "15"
            registry: docker_registry
            autoPull: true
      jfrogCliVersion: 2
      environmentVariables:
        readOnly:
          JFROG_TASK_DEBUG: "true"
          JFROG_CLI_LOG_LEVEL: debug
    steps:
      - name: gradle_build
        type: Bash
        configuration:
          inputResources:
            - name: gradle_build_task_gitrepo
            - name: gradle_app
          integrations:
            - name: int_default_artifactory
        execution:
          onStart:
            - curl -fL https://install-cli.jfrog.io | sh
            - jf --version
            - jf config show
            - gradle --version
          onExecute:
            - task: $res_gradle_build_task_gitrepo_resourcePath
              id: gradle-build-task
              input:
                deployerSnapshotRepo: {{ .Values.deployerRepo }}
                deployerReleaseRepo: {{ .Values.deployerRepo }}
                configFileLocation: /.jfrog/projects/
                configFileName: gradle.yaml
                resourceName: gradle_app
                sourceLocation: ""
                gradleCommand: "clean build"
